variable "region" {}
variable "project_name" {}
variable "domain_name" {}
variable "endpoint" {}
variable "key_name" {}
variable "instance_type" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}