variable "region" {}
variable "project_name" {}
variable "domain_name" {}
variable "endpoint" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
variable "repository_name" {}
variable "cluster_name" {}
variable "container_port" {}
variable "host_port" {}
variable "service_name" {}
